void FP_OPEN();
void FP_LED_open();
void FP_LED_close();
void FP_GetEnrollCount();
void FP_EnrollStart(int specify_ID);
void FP_Enroll(int Enroll_define);
void FP_IsPressFinger();
void FP_DeleteAll();
void FP_Identify();
void FP_CAPTUREFINGER(unsigned long picture_quality);
